package baseknowledge

// springdata.go — Spring Data repository knowledge pack (T9 #3841).
//
// Spring Data ships a repository interface hierarchy whose subinterfaces (a
// user's `interface UserRepo extends JpaRepository<User,Long> {}`) inherit a
// fixed set of CRUD/finder methods WITHOUT declaring any of them — the bodies
// are generated by Spring at runtime / live in the Spring Data jar, never in
// the indexed repo. The MRO walk needs each inherited method attributed to the
// defining interface plus its db read/write effect.
//
// Hierarchy (Spring Data Commons / Spring Data JPA):
//
//	Repository<T,ID>                         (marker, no members)
//	  └ CrudRepository<T,ID>                 save/saveAll/findById/existsById/
//	                                          findAll/findAllById/count/
//	                                          deleteById/delete/deleteAllById/
//	                                          deleteAll
//	      └ ListCrudRepository<T,ID>         (Spring Data 3: List-returning
//	                                          findAll/findAllById/saveAll)
//	  └ PagingAndSortingRepository<T,ID>     findAll(Sort)/findAll(Pageable)
//	      └ JpaRepository<T,ID>              + flush/saveAndFlush/
//	                                          deleteAllInBatch/
//	                                          deleteAllByIdInBatch/getById/
//	                                          getReferenceById  (getOne/getById
//	                                          deprecated aliases)
//
// We DO NOT fabricate HTTP statuses — these are data methods (Spring Data REST
// verb→status synthesis is T10 #3842's job). Each member carries db_read /
// db_write only.
//
// Sources: Spring Data Commons CrudRepository / PagingAndSortingRepository and
// Spring Data JPA JpaRepository Javadoc.

const (
	springDataRoot = "org.springframework.data.repository."
	springJpaRoot  = "org.springframework.data.jpa.repository."
)

// crudRepositoryMembers is the CrudRepository<T,ID> contract — the core CRUD
// surface every Spring Data repository inherits.
func crudRepositoryMembers(defining string) []Member {
	return []Member{
		dbWrite("save", defining, "persists (insert or update) the entity, returns the saved instance"),
		dbWrite("saveAll", defining, "persists all given entities"),
		dbRead("findById", defining, "returns Optional<T> by id"),
		dbRead("existsById", defining, "returns whether an entity with the id exists"),
		dbRead("findAll", defining, "returns all instances"),
		dbRead("findAllById", defining, "returns all instances for the given ids"),
		dbRead("count", defining, "returns the number of entities"),
		dbWrite("deleteById", defining, "deletes the entity with the given id"),
		dbWrite("delete", defining, "deletes the given entity"),
		dbWrite("deleteAllById", defining, "deletes all entities with the given ids"),
		dbWrite("deleteAll", defining, "deletes all entities"),
	}
}

// pagingAndSortingMembers adds the Sort/Pageable overloads of findAll.
func pagingAndSortingMembers(defining string) []Member {
	return []Member{
		dbRead("findAll", defining, "Sort/Pageable overload — returns all (sorted or as a Page)"),
	}
}

// jpaRepositoryExtraMembers adds the JPA-specific methods on top of CRUD +
// paging.
func jpaRepositoryExtraMembers(defining string) []Member {
	return []Member{
		dbWrite("flush", defining, "flushes pending changes to the database"),
		dbWrite("saveAndFlush", defining, "saves an entity and flushes immediately"),
		dbWrite("saveAllAndFlush", defining, "saves all entities and flushes immediately"),
		dbWrite("deleteAllInBatch", defining, "deletes all entities in a single batch DELETE"),
		dbWrite("deleteAllByIdInBatch", defining, "deletes the given ids in a single batch DELETE"),
		dbRead("getById", defining, "returns a reference to the entity by id (lazy proxy)"),
		dbRead("getReferenceById", defining, "returns a reference to the entity by id (replaces getOne/getById)"),
		dbRead("getOne", defining, "deprecated lazy reference accessor (use getReferenceById)"),
	}
}

// springDataPack is the Spring Data repository knowledge pack.
type springDataPack struct{}

func (springDataPack) Framework() string { return "spring-data" }

func (springDataPack) Contracts() []BaseClassContract {
	const (
		repoFQN  = springDataRoot + "Repository"
		crudFQN  = springDataRoot + "CrudRepository"
		listCrud = springDataRoot + "ListCrudRepository"
		pageFQN  = springDataRoot + "PagingAndSortingRepository"
		listPage = springDataRoot + "ListPagingAndSortingRepository"
		jpaFQN   = springJpaRoot + "JpaRepository"
	)

	// The effective member set a JpaRepository subclass sees: CRUD + paging +
	// JPA extras. We encode the FULL effective set on JpaRepository (the leaf a
	// user writes), each member attributed to the interface that actually
	// defines it, so the MRO walk resolves any inherited method in one lookup
	// without registry-side interface composition for external bases.
	jpaEffective := func() map[string]Member {
		all := append([]Member{}, crudRepositoryMembers(crudFQN)...)
		all = append(all, pagingAndSortingMembers(pageFQN)...)
		all = append(all, jpaRepositoryExtraMembers(jpaFQN)...)
		// findAll appears in both CRUD and paging; keep the CRUD (no-arg)
		// attribution as the canonical one — members() last-wins would otherwise
		// drop it, so put CRUD last by re-appending. Simpler: dedupe by name
		// keeping the first (CRUD) attribution.
		return dedupeByNameKeepFirst(all)
	}

	return []BaseClassContract{
		// Marker interface — known but contributes no members. Registered by FQN
		// ONLY (no bare "Repository" leaf): the bare leaf is reserved for
		// TypeORM's member-bearing Repository in nestjs.go, and shadowing it with
		// this empty marker would break TypeORM bare-leaf resolution. A Spring
		// `extends Repository<T>` is rare and still resolves via its FQN.
		dataContract("java", "spring-data", []string{repoFQN}, dataMembers()),

		dataContract("java", "spring-data", []string{crudFQN, "CrudRepository"},
			dataMembers(crudRepositoryMembers(crudFQN)...)),
		dataContract("java", "spring-data", []string{listCrud, "ListCrudRepository"},
			dataMembers(crudRepositoryMembers(listCrud)...)),

		dataContract("java", "spring-data", []string{pageFQN, "PagingAndSortingRepository"},
			dataMembers(pagingAndSortingMembers(pageFQN)...)),
		dataContract("java", "spring-data", []string{listPage, "ListPagingAndSortingRepository"},
			dataMembers(pagingAndSortingMembers(listPage)...)),

		dataContract("java", "spring-data", []string{jpaFQN, "JpaRepository"}, jpaEffective()),
	}
}

// dedupeByNameKeepFirst collapses members with the same Name, keeping the FIRST
// occurrence (so the canonical, most-general attribution wins over a later
// overload of the same name).
func dedupeByNameKeepFirst(ms []Member) map[string]Member {
	out := make(map[string]Member, len(ms))
	for _, m := range ms {
		if _, exists := out[m.Name]; exists {
			continue
		}
		out[m.Name] = m
	}
	return out
}

func init() { Register(springDataPack{}) }
